### ISSUE TITLE
An error is reported when running the demo

### ISSUE THREAD

**Issue by 834810269** [stevewongv/SSIS#10]
The prediction is {'instances': None}

`[03/22 21:39:26 detectron2]: Arguments: Namespace(config_file='../configs/SSIS/MS_R_101_BiFPN_SSISv2.yaml', webcam=False, video_input=None, input='./samples', output='./res/', confidence_threshold=0.1, opts=[])
WARNING [03/22 21:39:26 d2.config.compat]: Config '../configs/SSIS/MS_R_101_BiFPN_SSISv2.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[03/22 21:39:30 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from detectron2://ImageNetPretrained/MSRA/R-101.pkl ...
[03/22 21:39:30 d2.checkpoint.c2_model_loading]: Renaming Caffe2 weights ......
[03/22 21:39:30 d2.checkpoint.c2_model_loading]: Following weights matched with submodule backbone.bottom_up.backbone:
| Names in Model    | Names in Checkpoint       | Shapes                                          |
|:------------------|:--------------------------|:------------------------------------------------|
| res2.0.conv1.*    | res2_0_branch2a_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,64,1,1)             |
| res2.0.conv2.*    | res2_0_branch2b_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,64,3,3)             |
| res2.0.conv3.*    | res2_0_branch2c_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,64,1,1)        |
| res2.0.shortcut.* | res2_0_branch1_{bn_*,w}   | (256,) (256,) (256,) (256,) (256,64,1,1)        |
| res2.1.conv1.*    | res2_1_branch2a_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,256,1,1)            |
| res2.1.conv2.*    | res2_1_branch2b_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,64,3,3)             |
| res2.1.conv3.*    | res2_1_branch2c_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,64,1,1)        |
| res2.2.conv1.*    | res2_2_branch2a_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,256,1,1)            |
| res2.2.conv2.*    | res2_2_branch2b_{bn_*,w}  | (64,) (64,) (64,) (64,) (64,64,3,3)             |
| res2.2.conv3.*    | res2_2_branch2c_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,64,1,1)        |
| res3.0.conv1.*    | res3_0_branch2a_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,256,1,1)       |
| res3.0.conv2.*    | res3_0_branch2b_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,128,3,3)       |
| res3.0.conv3.*    | res3_0_branch2c_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,128,1,1)       |
| res3.0.shortcut.* | res3_0_branch1_{bn_*,w}   | (512,) (512,) (512,) (512,) (512,256,1,1)       |
| res3.1.conv1.*    | res3_1_branch2a_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,512,1,1)       |
| res3.1.conv2.*    | res3_1_branch2b_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,128,3,3)       |
| res3.1.conv3.*    | res3_1_branch2c_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,128,1,1)       |
| res3.2.conv1.*    | res3_2_branch2a_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,512,1,1)       |
| res3.2.conv2.*    | res3_2_branch2b_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,128,3,3)       |
| res3.2.conv3.*    | res3_2_branch2c_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,128,1,1)       |
| res3.3.conv1.*    | res3_3_branch2a_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,512,1,1)       |
| res3.3.conv2.*    | res3_3_branch2b_{bn_*,w}  | (128,) (128,) (128,) (128,) (128,128,3,3)       |
| res3.3.conv3.*    | res3_3_branch2c_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,128,1,1)       |
| res4.0.conv1.*    | res4_0_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,512,1,1)       |
| res4.0.conv2.*    | res4_0_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.0.conv3.*    | res4_0_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.0.shortcut.* | res4_0_branch1_{bn_*,w}   | (1024,) (1024,) (1024,) (1024,) (1024,512,1,1)  |
| res4.1.conv1.*    | res4_1_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.1.conv2.*    | res4_1_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.1.conv3.*    | res4_1_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.10.conv1.*   | res4_10_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.10.conv2.*   | res4_10_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.10.conv3.*   | res4_10_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.11.conv1.*   | res4_11_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.11.conv2.*   | res4_11_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.11.conv3.*   | res4_11_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.12.conv1.*   | res4_12_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.12.conv2.*   | res4_12_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.12.conv3.*   | res4_12_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.13.conv1.*   | res4_13_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.13.conv2.*   | res4_13_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.13.conv3.*   | res4_13_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.14.conv1.*   | res4_14_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.14.conv2.*   | res4_14_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.14.conv3.*   | res4_14_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.15.conv1.*   | res4_15_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.15.conv2.*   | res4_15_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.15.conv3.*   | res4_15_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.16.conv1.*   | res4_16_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.16.conv2.*   | res4_16_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.16.conv3.*   | res4_16_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.17.conv1.*   | res4_17_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.17.conv2.*   | res4_17_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.17.conv3.*   | res4_17_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.18.conv1.*   | res4_18_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.18.conv2.*   | res4_18_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.18.conv3.*   | res4_18_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.19.conv1.*   | res4_19_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.19.conv2.*   | res4_19_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.19.conv3.*   | res4_19_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.2.conv1.*    | res4_2_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.2.conv2.*    | res4_2_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.2.conv3.*    | res4_2_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.20.conv1.*   | res4_20_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.20.conv2.*   | res4_20_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.20.conv3.*   | res4_20_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.21.conv1.*   | res4_21_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.21.conv2.*   | res4_21_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.21.conv3.*   | res4_21_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.22.conv1.*   | res4_22_branch2a_{bn_*,w} | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.22.conv2.*   | res4_22_branch2b_{bn_*,w} | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.22.conv3.*   | res4_22_branch2c_{bn_*,w} | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.3.conv1.*    | res4_3_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.3.conv2.*    | res4_3_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.3.conv3.*    | res4_3_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.4.conv1.*    | res4_4_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.4.conv2.*    | res4_4_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.4.conv3.*    | res4_4_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.5.conv1.*    | res4_5_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.5.conv2.*    | res4_5_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.5.conv3.*    | res4_5_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.6.conv1.*    | res4_6_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.6.conv2.*    | res4_6_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.6.conv3.*    | res4_6_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.7.conv1.*    | res4_7_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.7.conv2.*    | res4_7_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.7.conv3.*    | res4_7_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.8.conv1.*    | res4_8_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.8.conv2.*    | res4_8_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.8.conv3.*    | res4_8_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res4.9.conv1.*    | res4_9_branch2a_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,1024,1,1)      |
| res4.9.conv2.*    | res4_9_branch2b_{bn_*,w}  | (256,) (256,) (256,) (256,) (256,256,3,3)       |
| res4.9.conv3.*    | res4_9_branch2c_{bn_*,w}  | (1024,) (1024,) (1024,) (1024,) (1024,256,1,1)  |
| res5.0.conv1.*    | res5_0_branch2a_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,1024,1,1)      |
| res5.0.conv2.*    | res5_0_branch2b_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,512,3,3)       |
| res5.0.conv3.*    | res5_0_branch2c_{bn_*,w}  | (2048,) (2048,) (2048,) (2048,) (2048,512,1,1)  |
| res5.0.shortcut.* | res5_0_branch1_{bn_*,w}   | (2048,) (2048,) (2048,) (2048,) (2048,1024,1,1) |
| res5.1.conv1.*    | res5_1_branch2a_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,2048,1,1)      |
| res5.1.conv2.*    | res5_1_branch2b_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,512,3,3)       |
| res5.1.conv3.*    | res5_1_branch2c_{bn_*,w}  | (2048,) (2048,) (2048,) (2048,) (2048,512,1,1)  |
| res5.2.conv1.*    | res5_2_branch2a_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,2048,1,1)      |
| res5.2.conv2.*    | res5_2_branch2b_{bn_*,w}  | (512,) (512,) (512,) (512,) (512,512,3,3)       |
| res5.2.conv3.*    | res5_2_branch2c_{bn_*,w}  | (2048,) (2048,) (2048,) (2048,) (2048,512,1,1)  |
| stem.conv1.norm.* | res_conv1_bn_*            | (64,) (64,) (64,) (64,)                         |
| stem.conv1.weight | conv1_w                   | (64, 3, 7, 7)                                   |
Some model parameters or buffers are not found in the checkpoint:
backbone.bottom_up.res6.reduction.norm.{bias, running_mean, running_var, weight}
backbone.bottom_up.res6.reduction.weight
backbone.repeated_bifpn.0.lateral_0_f0.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.lateral_0_f0.{bias, weight}
backbone.repeated_bifpn.0.lateral_1_f1.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.lateral_1_f1.{bias, weight}
backbone.repeated_bifpn.0.lateral_2_f2.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.lateral_2_f2.{bias, weight}
backbone.repeated_bifpn.0.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f0_0_7.weight
backbone.repeated_bifpn.0.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f1_1_6.weight
backbone.repeated_bifpn.0.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.0.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f2_2_5.weight
backbone.repeated_bifpn.0.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.0.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f3_3_4.weight
backbone.repeated_bifpn.0.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.0.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.0.outputs_f4_4_11.weight
backbone.repeated_bifpn.0.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
backbone.repeated_bifpn.1.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f0_0_7.weight
backbone.repeated_bifpn.1.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f1_1_6.weight
backbone.repeated_bifpn.1.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.1.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f2_2_5.weight
backbone.repeated_bifpn.1.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.1.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f3_3_4.weight
backbone.repeated_bifpn.1.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.1.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.1.outputs_f4_4_11.weight
backbone.repeated_bifpn.1.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
backbone.repeated_bifpn.2.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f0_0_7.weight
backbone.repeated_bifpn.2.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f1_1_6.weight
backbone.repeated_bifpn.2.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.2.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f2_2_5.weight
backbone.repeated_bifpn.2.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.2.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f3_3_4.weight
backbone.repeated_bifpn.2.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.2.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.2.outputs_f4_4_11.weight
backbone.repeated_bifpn.2.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
backbone.repeated_bifpn.3.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f0_0_7.weight
backbone.repeated_bifpn.3.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f1_1_6.weight
backbone.repeated_bifpn.3.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.3.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f2_2_5.weight
backbone.repeated_bifpn.3.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.3.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f3_3_4.weight
backbone.repeated_bifpn.3.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.3.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.3.outputs_f4_4_11.weight
backbone.repeated_bifpn.3.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
backbone.repeated_bifpn.4.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f0_0_7.weight
backbone.repeated_bifpn.4.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f1_1_6.weight
backbone.repeated_bifpn.4.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.4.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f2_2_5.weight
backbone.repeated_bifpn.4.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.4.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f3_3_4.weight
backbone.repeated_bifpn.4.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.4.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.4.outputs_f4_4_11.weight
backbone.repeated_bifpn.4.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
backbone.repeated_bifpn.5.outputs_f0_0_7.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f0_0_7.weight
backbone.repeated_bifpn.5.outputs_f1_1_6.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f1_1_6.weight
backbone.repeated_bifpn.5.outputs_f1_1_7_8.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f1_1_7_8.weight
backbone.repeated_bifpn.5.outputs_f2_2_5.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f2_2_5.weight
backbone.repeated_bifpn.5.outputs_f2_2_6_9.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f2_2_6_9.weight
backbone.repeated_bifpn.5.outputs_f3_3_4.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f3_3_4.weight
backbone.repeated_bifpn.5.outputs_f3_3_5_10.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f3_3_5_10.weight
backbone.repeated_bifpn.5.outputs_f4_4_11.norm.{bias, running_mean, running_var, weight}
backbone.repeated_bifpn.5.outputs_f4_4_11.weight
backbone.repeated_bifpn.5.{weights_f0_0_7, weights_f1_1_6, weights_f1_1_7_8, weights_f2_2_5, weights_f2_2_6_9, weights_f3_3_4, weights_f3_3_5_10, weights_f4_4_11}
controller.{bias, weight}
controller2.{bias, weight}
mask_branch.refine.0.0.weight
mask_branch.refine.0.1.{bias, running_mean, running_var, weight}
mask_branch.refine.1.0.weight
mask_branch.refine.1.1.{bias, running_mean, running_var, weight}
mask_branch.refine.2.0.weight
mask_branch.refine.2.1.{bias, running_mean, running_var, weight}
mask_branch.tower.0.0.weight
mask_branch.tower.0.1.{bias, running_mean, running_var, weight}
mask_branch.tower.1.0.weight
mask_branch.tower.1.1.{bias, running_mean, running_var, weight}
mask_branch.tower.2.0.weight
mask_branch.tower.2.1.{bias, running_mean, running_var, weight}
mask_branch.tower.3.0.weight
mask_branch.tower.3.1.{bias, running_mean, running_var, weight}
mask_branch.tower.4.{bias, weight}
mask_head.maskiou_head.conv.{bias, weight}
mask_head.maskiou_head.conv1x1_1.{bias, weight}
mask_head.maskiou_head.conv1x1_2.{bias, weight}
mask_head.maskiou_head.conv_offset.weight
mask_head.maskiou_head.maskiou.{bias, weight}
mask_head.maskiou_head.maskiou_deformfcn1.{bias, weight}
mask_head.maskiou_head.maskiou_deformfcn2.{bias, weight}
mask_head.maskiou_head.maskiou_deformfcn3.{bias, weight}
mask_head.maskiou_head.maskiou_deformmask1.weight
mask_head.maskiou_head.maskiou_fc1.{bias, weight}
mask_head.maskiou_head.maskiou_fc2.{bias, weight}
mask_head.{sizes_of_interest, strides}
proposal_generator.fcos_head.bbox_pred.{bias, weight}
proposal_generator.fcos_head.bbox_tower.0.{bias, weight}
proposal_generator.fcos_head.bbox_tower.1.{bias, weight}
proposal_generator.fcos_head.bbox_tower.10.{bias, weight}
proposal_generator.fcos_head.bbox_tower.3.{bias, weight}
proposal_generator.fcos_head.bbox_tower.4.{bias, weight}
proposal_generator.fcos_head.bbox_tower.6.{bias, weight}
proposal_generator.fcos_head.bbox_tower.7.{bias, weight}
proposal_generator.fcos_head.bbox_tower.9.{bias, weight}
proposal_generator.fcos_head.cls_logits.{bias, weight}
proposal_generator.fcos_head.cls_tower.0.{bias, weight}
proposal_generator.fcos_head.cls_tower.1.{bias, weight}
proposal_generator.fcos_head.cls_tower.10.{bias, weight}
proposal_generator.fcos_head.cls_tower.3.{bias, weight}
proposal_generator.fcos_head.cls_tower.4.{bias, weight}
proposal_generator.fcos_head.cls_tower.6.{bias, weight}
proposal_generator.fcos_head.cls_tower.7.{bias, weight}
proposal_generator.fcos_head.cls_tower.9.{bias, weight}
proposal_generator.fcos_head.ctrness.{bias, weight}
proposal_generator.fcos_head.offset_pred.{bias, weight}
proposal_generator.fcos_head.scales.0.scale
proposal_generator.fcos_head.scales.1.scale
proposal_generator.fcos_head.scales.2.scale
proposal_generator.fcos_head.scales.3.scale
proposal_generator.fcos_head.scales.4.scale
The checkpoint state_dict contains keys that are not used by the model:
  fc1000.{bias, weight}
  0%|                                                               | 0/4 [00:00<?, ?it/s]/home/xyw/miniconda3/envs/pytorch111/lib/python3.9/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646756402876/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
{'instances': None}
instances
  0%|                                                               | 0/4 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/raid/xiayuwei/code/SSIS/demo/demo.py", line 93, in <module>
    instances, visualized_output = demo.run_on_image(img)
  File "/raid/xiayuwei/code/SSIS/demo/predictor.py", line 83, in run_on_image
    instances.pred_masks = instances.pred_masks.numpy()
AttributeError: 'NoneType' object has no attribute 'pred_masks'`

**Comment by stevewongv** [comment]
Currently, you load the backbone weight to the network, so it cannot output correct results. You need to download the weight first.

**Comment by 834810269** [comment]
> Currently, you load the backbone weight to the network, so it cannot output correct results. You need to download the weight first.


Thanks for your reply！Where should I load the weights in demo.py. I have downloaded the pre-trained model according to the readme and put it in the specified path.

**Comment by stevewongv** [comment]
> > Currently, you load the backbone weight to the network, so it cannot output correct results. You need to download the weight first.
> 
> 
> 
> 
> 
> Thanks for your reply！Where should I load the weights in demo.py. I have downloaded the pre-trained model according to the readme and put it in the specified path.

See the yaml file: configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml

**Comment by 834810269** [comment]
> > > Currently, you load the backbone weight to the network, so it cannot output correct results. You need to download the weight first.
> > 
> > 
> > Thanks for your reply！Where should I load the weights in demo.py. I have downloaded the pre-trained model according to the readme and put it in the specified path.
> 
> See the yaml file: configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml

Thanks a lot！
