### ISSUE TITLE
How to configure data for training on custom dataset?

### ISSUE THREAD

**Issue by ns-tm42** [stevewongv/SSIS#12]
I would like to retrain the model on a custom dataset. I have recreated the json format that is provided in ./dataset/SOBA/annotations/ and I have my images saved similar to that as shown in ./dataset/SOBA/SOBA/challenge/ . 

How should I format my config.yaml for training?

**Comment by stevewongv** [comment]
You need to use `register_soba_instances` function in `tools/train_net.py` to register the dataset:
https://github.com/stevewongv/SSIS/blob/943f87d9823d3dd994077be1f31f90644a6f47a1/tools/train_net.py#L57
