### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jalemann** [stevewongv/SSIS#13]
Hey there, the demo is not working locally nor in colab.

Following the notebook in colab the following error message is returned:
```sh
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the `__init__` method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "
[08/07 11:11:49 detectron2]: Arguments: Namespace(config_file='../configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml', webcam=False, video_input=None, input='./samples', output='./res/', confidence_threshold=0.1, opts=[])
WARNING [08/07 11:11:49 d2.config.compat]: Config '../configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[08/07 11:11:50 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from ../tools/output/SSISv2_MS_R_101_bifpn_with_offset_class_maskiouv2_da_bl/model_ssisv2_final.pth ...
  0% 0/4 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
double free or corruption (!prev)
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Similarly I tried to run the demo locally following the instructions in the README (using CUDA 11.3 and torch 1.11.0 both of which should be supported according to the README) and it returns a similar  error:
```sh
alemann@n02-01:~/SSIS/demo$ python3 demo.py --input ./samples/

[07/31 13:47:09 detectron2]: Arguments: Namespace(confidence_threshold=0.1, config_file='../configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml', input='./samples/', opts=[], output='./res/', video_input=None, webcam=False)

WARNING [07/31 13:47:09 d2.config.compat]: Config '../configs/SSIS/MS_R_101_BiFPN_SSISv2_demo.yaml' has no VERSION. Assuming it to be compatible with latest v2.

[07/31 13:47:21 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from ../tools/output/SSISv2_MS_R_101_bifpn_with_offset_class_maskiouv2_da_bl/model_ssisv2_final.pth ...

  0%|                                                                   | 0/4 [00:00<?, ?it/s]/scratch/alemann/python/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)

  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

double free or corruption (!prev)

/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

  warnings.warn('resource_tracker: There appear to be %d '

Aborted
```

**Comment by stevewongv** [comment]
It's related to a known issue in pysobatools in python 3.10. You can try this workaround: https://github.com/stevewongv/InstanceShadowDetection/issues/24#issuecomment-1668927882

**Comment by jalemann** [comment]
The workaround did solve the error.
However I had to remove the whole SSIS dir and install and build everything again or else the build of pysobatools would fail, just a FYI if anyone stumbles across the same thing.

**Comment by jalemann** [comment]
Oh right, I probably should mention that I only tried this workaround on my local setup where I edited the `requirement.txt` file.

On Colab I just tried something similar to @yudi-xiao and got the same error.
Therefore I am reopening this issue.

**Comment by aviadmx** [comment]
> The workaround did solve the error. Thank you! However I had to remove the whole SSIS dir and install and build everything again or else the build of pysobatools would fail, just a FYI if anyone stumbles across the same thing.

Could you please specifiy what exactly you did to install pysobatools successfully? Like, step by step? Thanks!

**Comment by aviadmx** [comment]
@stevewongv Also occurs in python 3.9

**Comment by jalemann** [comment]
@aviadmx Sure, here is what I did step-by-step. Keep in mind that it worked on my setup not in Colab.

0. Delete everything to start from scratch.
1. Download repo (e.g. with `wget https://github.com/stevewongv/SSIS/archive/refs/heads/main.zip`)
2. (Might be skippable) Unzip repo if it was downloaded as zip, also rename it to `SSIS` if it was named differently
3. `cd` into the repo directory
4. Create a virtual environment (e.g. with `python3 -m venv venv`) and activate it
5. Installing those as it didn't work for me without`pip install onnx protobuf`
6. Install an appropriate Torch version (e.g. `pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113` for torch 1.11.0 and CUDA 11.3, look up what you need and find the command [here](https://pytorch.org/get-started/previous-versions/))
7. Apply the workaround mentioned [here](https://github.com/stevewongv/InstanceShadowDetection/issues/24#issuecomment-1668927882) by editing the `requirement.txt` file and replacing `git+https://github.com/stevewongv/InstanceShadowDetection.git#subdirectory=PythonAPI` with `git+https://github.com/stevewongv/InstanceShadowDetection.git@50764eb336f3194db382054fe537956dd8449c01#subdirectory=PythonAPI`
8. Install the requirements: `pip install -r requirement.txt`
9. Run setup (something like this `python3 setup.py build develop -d /path/depends/on/your/setup/python3.8/site-packages/`, note to change the path according to your Python installation)
10. `pip install opencv-python`

That's probably it. I came across some more pip errors at some point which I just fixed by uninstalling and installing everything it showed errors for.

**Comment by stevewongv** [comment]
I have just fixed the demo in Colab. It was a bit strange when building the pysobatools, but I managed to fix it by using a workaround.

**Comment by jalemann** [comment]
@stevewongv Thanks again!
