### ISSUE TITLE
how to predict the new shadow in another picture?

### ISSUE THREAD

**Issue by xdg2016** [stevewongv/SSIS#15]
Thank you for your research results. I would like to ask how to use SSIS to predict a new shadow of an object in another image (the new shadow is consistent with the shadows of other objects in the image)，thanks

**Comment by stevewongv** [comment]
Do you mean you want to track this object in different frames?

**Comment by xdg2016** [comment]
No, I want to move an object to a new image. How can I generate its correct shadow in the new image? just like (d) in the paper
![image](https://github.com/stevewongv/SSIS/assets/16351823/a3cb4ada-6869-43ba-a94a-15f4773aa0fa)

**Comment by stevewongv** [comment]
Here is a simple solution: First, you need to perform instance shadow detection for each image. Then you can do the affine transformation based on the prediction (i.e. the scale and shape of bbox for objects/shadows.). You need to first rotate the shadow and re-scale it.

**Comment by xdg2016** [comment]
thanks，I'll try it
