### ISSUE TITLE
problem with train

### ISSUE THREAD

**Issue by JR-Guo** [stevewongv/SSIS#2]
I encounter a problem when i reproduce your code.

in ./adet/modeling/ssis/condinst.py line 96 in forward
loss_mask,loss_asso_mask,asso_offset_losses, loss_maskiou, association_masks_loss = self._forward_mask_heads_train(proposals, mask_feats, gt_instances)

not enough values to upack (expected 5, got 3)
Do you have any idea about this problem?

**Comment by stevewongv** [comment]
Thank you for your report. I have fixed this in the latest commit.
