### ISSUE TITLE
How to generate the corresponding shadow based on the composite image

### ISSUE THREAD

**Issue by zhanghongyong123456** [stevewongv/SSIS#3]
Can this project achieve shadow generation，like this
![image](https://user-images.githubusercontent.com/48466610/144979005-a766e222-bf46-44d5-a0d6-037e9c87cd8c.png)
I want to generate corresponding shadows based on the composite image,

**Comment by stevewongv** [comment]
Nope, this project mainly focuses on **instance shadow detection** which aims to find shadow instances with its corresponding object instances. I think the predicted the masks of shadow instances and objects instances of our method can help to network to generate the corresponding shadow for the input object.

**Comment by zhanghongyong123456** [comment]
> Nope, this project mainly focuses on **instance shadow detection** which aims to find shadow instances with their corresponding object instances. I think the predicted the masks of shadow instances and objects instances of our method can help the network to generate the corresponding shadow for the input object.


1.Is there any good algorithm recommendation for shadow generation, thank you，
2. got the shadow and the object, how do I take them out separately
![image](https://user-images.githubusercontent.com/48466610/144980985-bf1d5946-9061-4e0b-9030-ca1824ea8426.png)

**Comment by stevewongv** [comment]
For question one, I think you can check the papers from CVPR, ICCV and ECCV.
For question two, with the masks, you can separate them directly by `shadow/object = image X mask `

**Comment by zhanghongyong123456** [comment]
> image

Ok, thank you very much for your reply
