### ISSUE TITLE
about  install  project  (python setup.py build develop) ,error  , python 3.9  pytorch 1.9  cuda 11.1  ,because  when pip install requirement.txt  need  pytorch >=1.8.1,so   i  pip   pyotrch 1.9

### ISSUE THREAD

**Issue by zhanghongyong123456** [stevewongv/SSIS#6]
![image](https://user-images.githubusercontent.com/48466610/196109860-5722e3eb-5a28-49d2-80c3-1b72581f2471.png)

**Comment by stevewongv** [comment]
Oh sorry, I just find this is related to the issue https://github.com/aim-uofa/AdelaiDet/pull/518. I think you should use PyTorch 1.11+. I will update the README.

**Comment by stevewongv** [comment]
You only need to replace the folder adet/layers/*

**Comment by zhanghongyong123456** [comment]
> You only need to replace the folder adet/layers/*
thank you very much
ok,it's  run on python3.9  pytorch1.9 cuda11.1   ,have a few questions
1.Test my own video, some objects cannot be detected, how can I improve it?
2.What is the fps of our project, can it reach 4k real time?

**Comment by stevewongv** [comment]
You could email me for further discussion. I will close this issue first.

**Comment by ai1361720220000** [comment]
i meet the same question when torch=1.10
