### ISSUE TITLE
[Question] How to use copy-and-paste augmentation 

### ISSUE THREAD

**Issue by kiraicode** [stevewongv/SSIS#8]
Hi, thanks for the great work! I just came across the copy-and-paste augmentation in your paper and I think it's a really good idea. I would like to apply it to my personal dataset with contains very few objects in each image (traffic cones). Do you have an example of how to use this transformation on an image? Thanks in advance!

**Comment by stevewongv** [comment]
See the code around this line https://github.com/stevewongv/SSIS/blob/aa6ddc7f05f91c0d1d1b5529f5090ded3686cbbf/adet/data/dataset_mapper.py#L300
